algo= input( 'Digite algo: ')
print(type(algo))
print('Só tem espaço?',algo.isspace())
print('É númerico?',algo.isnumeric())
print('É alfabético?',algo.isalpha())
print('É alfanumérico?',algo.isalnum())
print('É maiúsculo?',algo.isupper())
print('É minúsculo?',algo.islower())
print('Está capitaliizada?',algo.istitle())